### PR TITLE
Remove deprecated XdgDesktopFileCache

### PR DESCRIPTION
**Pull request by luis-pereira**
Deprecated roughly two years ago. It's time to let it go.

### CODE REVIEW

**Comment by luis-pereira** [comment]
To be merge after the 0.16 release

**Comment by tsujan** [comment]
The code looks good. Will test it tomorrow.

**Comment by palinek** [comment]
Shouldn't be bumping the .so version part of this PR?

**Comment by tsujan** [comment]
> Shouldn't be bumping the .so version part of this PR?

It's usually done before the next release -- at least, that has been the case with libfm-qt.

**Comment by luis-pereira** [comment]
In addition to @tsujan comments, the class in question wasn't exported, it shouldn't break binary compatibility.

**Review by tsujan — APPROVED** [review]
GTM.

**Pull request merged**
