### PR TITLE
Remove obsolete qSwap

### PR DESCRIPTION
**Pull request by luis-pereira**
Use std::swap instead.

### CODE REVIEW

**Comment by yan12125** [comment]
This change appears to break compilation of lxqt-config and lxqt-panel. Here is an error from lxqt-panel:
```
[ 43%] Building CXX object lxqt-config-file-associations/CMakeFiles/lxqt-config-file-associations.dir/lxqt-config-file-associations_autogen/mocs_compilation.cpp.o                                                                                                
In file included from /usr/include/qt/QtCore/qlocale.h:46,
                 from /usr/include/qt/QtGui/qguiapplication.h:47,
                 from /usr/include/qt/QtWidgets/qapplication.h:52,
                 from /usr/include/qt/QtWidgets/QApplication:1,
                 from /home/yen/Computer/lxqt/lxqt-config/build/lxqt-config-file-associations/lxqt-config-file-associations_autogen/include/ui_applicationchooser.h:13,
                 from /home/yen/Computer/lxqt/lxqt-config/lxqt-config-file-associations/applicationchooser.h:29,
                 from /home/yen/Computer/lxqt/lxqt-config/build/lxqt-config-file-associations/lxqt-config-file-associations_autogen/EWIEGA46WW/moc_applicationchooser.cpp:10,
                 from /home/yen/Computer/lxqt/lxqt-config/build/lxqt-config-file-associations/lxqt-config-file-associations_autogen/mocs_compilation.cpp:2:
/usr/include/qt/QtCore/qshareddata.h: In instantiation of 'QExplicitlySharedDataPointer<T>::~QExplicitlySharedDataPointer() [with T = XdgMimeTypePrivate]':
/usr/include/c++/9.2.0/bits/move.h:193:11:   required from 'typename std::enable_if<std::__and_<std::__not_<std::__is_tuple_like<_Tp> >, std::is_move_constructible<_Tp>, std::is_move_assignable<_Tp> >::value>::type std::swap(_Tp&, _Tp&) [with _Tp = QExplicitlySharedDataPointer<XdgMimeTypePrivate>; typename std::enable_if<std::__and_<std::__not_<std::__is_tuple_like<_Tp> >, std::is_move_constructible<_Tp>, std::is_move_assignable<_Tp> >::value>::type = void]'
/usr/include/qt5xdg/xdgmimetype.h:88:31:   required from here
/usr/include/qt/QtCore/qshareddata.h:184:59: error: invalid use of incomplete type 'class XdgMimeTypePrivate'
  184 |     inline ~QExplicitlySharedDataPointer() { if (d && !d->ref.deref()) delete d; }
      |                                                        ~~~^~~
In file included from /usr/include/qt5xdg/XdgMimeType:1,
                 from /home/yen/Computer/lxqt/lxqt-config/lxqt-config-file-associations/applicationchooser.h:31,
                 from /home/yen/Computer/lxqt/lxqt-config/build/lxqt-config-file-associations/lxqt-config-file-associations_autogen/EWIEGA46WW/moc_applicationchooser.cpp:10,
                 from /home/yen/Computer/lxqt/lxqt-config/build/lxqt-config-file-associations/lxqt-config-file-associations_autogen/mocs_compilation.cpp:2:
/usr/include/qt5xdg/xdgmimetype.h:34:7: note: forward declaration of 'class XdgMimeTypePrivate'
   34 | class XdgMimeTypePrivate;
      |       ^~~~~~~~~~~~~~~~~~
```
Other errors are similar. If I revert libqtxdg to 6f597b30cef2bdefc9ca5362cdf195294ebb9556, building lxqt-panel is fine.

My environment: Arch Linux, GCC 9.2.0, Qt 5.14.0, lxqt packages are all git-master

**Comment by agaida** [comment]
Will check it later. in transit to Berlin - @luis-pereira - any idea?

**Comment by luis-pereira** [comment]
@agaida Not really. I'm away from my dev machine until 7 January.
Using Qt5.11 and gcc 7.0 it builds fine.
Revert if needed.

**Comment by yan12125** [comment]
Here you go~ https://github.com/lxqt/libqtxdg/pull/199

I suspect new libstdc++ from GCC is also relevant, but fixing it is beyond my ability :/

**Pull request merged**
