### PR TITLE
Prepared release 3.4.0

### PR DESCRIPTION
**Pull request by agaida**
- Added the changelog for the release
- Removed build type setting, already done in lxqt build tools
- Added .mailmap as export-ignore
- Bumped the minor version to 4

### CODE REVIEW

**Comment by agaida** [comment]
@tsujan - can you have a look?
https://github.com/lxqt/lxqt.github.io/blob/master/_posts/2019-10-27-libqtxdg-3.4.0.md

ok, our website looks horrible, i should play a bit with CSS

**Comment by tsujan** [comment]
I didn't find any problem in `2019-10-27-libqtxdg-3.4.0.md`. If you mean a specific issue, please tell me.

**Comment by agaida** [comment]
it was only about a second pair of eyes. Thanks.

**Comment by tsujan** [comment]
Please also note that I didn't recompile related components against it.

**Comment by agaida** [comment]
There should be no problem, only additional new symbols:
``` diff
+++ b/debian/libqt5xdg3.symbols
@@ -116,6 +116,23 @@ libQt5Xdg.so.3 libqt5xdg3 #MINVER#
  (c++)"XdgMenuWidget::qt_metacast(char const*)@Base" 1.0.0
  (c++)"XdgMenuWidget::staticMetaObject@Base" 1.0.0
  (c++)"XdgMenuWidget::~XdgMenuWidget()@Base" 1.0.0
+ (c++)"XdgMimeApps::XdgMimeApps(QObject*)@Base" 3.4.0~
+ (c++)"XdgMimeApps::addSupport(QString const&, XdgDesktopFile const&)@Base" 3.4.0~
+ (c++)"XdgMimeApps::allApps()@Base" 3.4.0~
+ (c++)"XdgMimeApps::apps(QString const&)@Base" 3.4.0~
+ (c++)"XdgMimeApps::categoryApps(QString const&)@Base" 3.4.0~
+ (c++)"XdgMimeApps::changed()@Base" 3.4.0~
+ (c++)"XdgMimeApps::defaultApp(QString const&)@Base" 3.4.0~
+ (c++)"XdgMimeApps::fallbackApps(QString const&)@Base" 3.4.0~
+ (c++)"XdgMimeApps::metaObject() const@Base" 3.4.0~
+ (c++)"XdgMimeApps::qt_metacall(QMetaObject::Call, int, void**)@Base" 3.4.0~
+ (c++)"XdgMimeApps::qt_metacast(char const*)@Base" 3.4.0~
+ (c++)"XdgMimeApps::recommendedApps(QString const&)@Base" 3.4.0~
+ (c++)"XdgMimeApps::removeSupport(QString const&, XdgDesktopFile const&)@Base" 3.4.0~
+ (c++)"XdgMimeApps::reset(QString const&)@Base" 3.4.0~
+ (c++)"XdgMimeApps::setDefaultApp(QString const&, XdgDesktopFile const&)@Base" 3.4.0~
+ (c++)"XdgMimeApps::staticMetaObject@Base" 3.4.0~
+ (c++)"XdgMimeApps::~XdgMimeApps()@Base" 3.4.0~
  (c++)"XdgMimeType::XdgMimeType()@Base" 1.0.0
  (c++)"XdgMimeType::XdgMimeType(QMimeType const&)@Base" 1.0.0
  (c++)"XdgMimeType::XdgMimeType(XdgMimeType const&)@Base" 1.0.0
@@ -129,14 +146,16 @@ libQt5Xdg.so.3 libqt5xdg3 #MINVER#
  (c++)"typeinfo for XdgIcon@Base" 1.0.0
  (c++)"typeinfo for XdgMenu@Base" 1.0.0
  (c++)"typeinfo for XdgMenuWidget@Base" 1.0.0
+ (c++)"typeinfo for XdgMimeApps@Base" 3.4.0~
  (c++)"typeinfo name for XdgAction@Base" 1.0.0
  (c++)"typeinfo name for XdgDesktopFile@Base" 1.0.0
  (c++)"typeinfo name for XdgIcon@Base" 1.0.0
  (c++)"typeinfo name for XdgMenu@Base" 1.0.0
  (c++)"typeinfo name for XdgMenuWidget@Base" 1.0.0
+ (c++)"typeinfo name for XdgMimeApps@Base" 3.4.0~
  (c++)"vtable for XdgAction@Base" 1.0.0
  (c++)"vtable for XdgDesktopFile@Base" 1.0.0
  (c++)"vtable for XdgIcon@Base" 1.0.0
  (c++)"vtable for XdgMenu@Base" 1.0.0
  (c++)"vtable for XdgMenuWidget@Base" 1.0.0
+ (c++)"vtable for XdgMimeApps@Base" 3.4.0~
```

**Pull request merged**
