### PR TITLE
Invalidate GTK icon cache as soon as icons are installed

### PR DESCRIPTION
**Pull request by tsujan**
Monitoring the GTK cache itself wasn't enough for showing real icons of newly installed apps (in Main Menu). Contrary to my expectations, the reason was that the cache was invalidated too late.

Here, the folder is monitored instead, and the cache is invalidated as soon as something happens inside the folder. It will be validated again when it's updated.

Closes https://github.com/lxqt/libqtxdg/issues/226

### CODE REVIEW

**Comment by Dami-star** [comment]
I have verified that the multiple installs of the application so far are fine

**Comment by tsujan** [comment]
@Dami-star 
Thank you very much for the tests!

The core idea of this patch is yours. Here I just went in the opposite direction of what I did before.

I also installed (and uninstalled) ~15 apps after applying the patch, and their icons were shown correctly, both in Main Menu and in pcmanfm-qt. Considering your results alongside mine, I think this is the solution we searched for :)

**Comment by Dami-star** [comment]
> @Dami-star Thank you very much for the tests!
> 
> The core idea of this patch is yours. Here I just went in the opposite direction of what I did before.
> 
> I also installed (and uninstalled) ~15 apps after applying the patch, and their icons were shown correctly, both in Main Menu and in pcmanfm-qt. Considering your results alongside mine, I think this is the solution we searched for :)

Great + 1, I also agree with this solution, I have tested and verified it under different architectures, and no problems have been found so far.

**Comment by tsujan** [comment]
Any objection to merging this?

**Pull request merged**
