### PR TITLE
Xdg default apps

### PR DESCRIPTION
**Pull request by luis-pereira**

### CODE REVIEW

**Comment by tsujan** [comment]
Very good. After this, `lxqt-config-file-associations` can be simplified and enhanced a little.

With the default browser being recognized, isn't it better to add the default email client and file manager to `XdgDefaultApps` too?

**Comment by luis-pereira** [comment]
> With the default browser being recognized, isn't it better to add the default email client and file manager to `XdgDefaultApps` too?

That's the plan. Dd not had the time, tough.

**Comment by tsujan** [comment]
> That's the plan. Dd not had the time, tough.

There's no hurry. When your work is finished, I'll modify the code of `lxqt-config-file-associations`.

**Comment by luis-pereira** [comment]
> There's no hurry. When your work is finished, I'll modify the code of `lxqt-config-file-associations`.

Sure. This is a draft still. Didn't mark it as such, tough.

**Comment by luis-pereira** [comment]
@tsujan Done.

**Pull request merged**
