### PR TITLE
Fixed a bug in supporting string literals in Exec keys

### PR DESCRIPTION
**Pull request by tsujan**
The code partially affected non-Exec keys too. This patch solves the problem by fully separating Exec keys from others.

Fixes https://github.com/lxqt/lxqt-panel/issues/1737

### CODE REVIEW

**Review by stefonarch — APPROVED** [review]
Issue with apostrophe is fixed, tor browser desktop file works still too.

**Comment by tsujan** [comment]
You did a great detective job, finding the problem with apostrophe. I enjoyed it.

> tor browser desktop file works still too.

Yes, I didn't touch that part of https://github.com/lxqt/libqtxdg/pull/271.

**Comment by tsujan** [comment]
I'll merge it tomorrow; want to take another look at it when I'm not drowsy ;)

**Comment by tsujan** [comment]
> But it was @slidinghotdog who gave the final hint.

Yes. He and I thought about the same thing almost simultaneously. But 90% of the problem was already solved by your finding.

**Pull request merged**
