### PR TITLE
Tools split

### PR DESCRIPTION
**Pull request by luis-pereira**

### CODE REVIEW

**Review by tsujan — APPROVED** [review]
I installed this and https://github.com/lxqt/qtxdg-tools and recompiled all LXQt components that needed `libqtxdg`. Everything works fine. `xdg-utils` also works fine with your patch (that uses `qtxdg-mat`).

**Comment by tsujan** [comment]
@yan12125 made a very good point at https://github.com/lxqt/lxqt/discussions/2139; I almost forgot about `lxqt-qtxdg.conf` and `qtxdg.conf`, although I'd skipped them alongside `qtxdg-mat` in https://github.com/lxqt/libqtxdg/pull/272.

It seems to me that we have to move them to `qtxdg-tools` too.

**Comment by tsujan** [comment]
@luis-pereira 
Please merge it if it's ready.

**Comment by yan12125** [comment]
Tested - the new CMake option work as intended, thanks!

**Comment by tsujan** [comment]
If we merge this before LXQt 1.1.0, we should also merge https://github.com/lxqt/qtxdg-tools/pull/2 and add `qtxdg-tools` as a dependency to `lxqt-session` (because `xdg-utils` will need it under an LXQt session when https://gitlab.freedesktop.org/xdg/xdg-utils/-/merge_requests/48 is merged).

**Comment by tsujan** [comment]
Please do not merge this PR before LXQt 1.1.0 is released! We will discuss it soon.

**Comment by tsujan** [comment]
I wonder why GitHub doesn't show a merge conflict here! This is impossible now:

```diff
- set(QTXDG_MINOR_VERSION 8)
+ set(QTXDG_MINOR_VERSION 9)
```

**Comment by tsujan** [comment]
Added a commit for bumping `LXQTBT_MINIMUM_VERSION` to 0.11.0.

I'll set `QTXDG_PATCH_VERSION` to 1 when making prerelease changes.

**Comment by tsujan** [comment]
After a commit for updating CHANGELOG, I think it's completely rebased now.

**Comment by tsujan** [comment]
Merging?

**Comment by yan12125** [comment]
Go ahead!

**Pull request merged**
